language: node_js
node_js:
  - 0.8
  - 6
  - 8
  - 10
  - 14
before_install:
  - npm install qnit
after_success:
  - if [ `node -p 'process.version.slice(0, 3)'` != "v8." ]; then exit; fi
  - npm install -g nyc codecov coveralls
  - npm run coverage
  - nyc report -r text-lcov | coveralls
